{
  parserUtilClass="org.neo4j.cypher.lang.parser.CypherParserUtil"
  parserClass="org.neo4j.cypher.lang.parser.CypherParser"
  parserImports=[
          "static org.neo4j.cypher.lang.parser.CypherParserTypes.*"
  ]

  psiPackage="org.neo4j.cypher.lang.psi"
  psiImplPackage="org.neo4j.cypher.lang.psi.impl"
  elementTypeHolderClass="org.neo4j.cypher.lang.parser.CypherParserTypes"

  tokenTypeClass="org.neo4j.cypher.lang.psi.CypherTokeType"

  tokens=[
    CREATE="CREATE"
    CONSTRAINT="CONSTRAINT"
    ASSERT="ASSERT"
    ON="ON"
    LPAR="("
    RPAR=")"
    IS="IS"
    UNIQUE="UNIQUE"
    INDEX="INDEX"
    DROP="DROP"

    //literals
    ID="regexp:\p{Alpha}\w*"
    COLON=":"
    DOT="."
  ]
}

chyper ::= command //| query
command ::= CreateUniqueConstraint |DropUniqueConstraint | CreateIndex | DropIndex
DropUniqueConstraint ::= DROP constraintSyntax
CreateUniqueConstraint ::= CREATE constraintSyntax
constraintSyntax ::= CONSTRAINT ON LPAR ID NodeLabel RPAR ASSERT? ID DOT ID IS UNIQUE

CreateIndex ::= CREATE INDEX ON NodeLabel LPAR ID RPAR
DropIndex ::= DROP INDEX ON NodeLabel LPAR ID RPAR

NodeLabel ::= COLON ID

//query ::=


// LITERALS
// org.neo4j.cypher.internal.parser.v2_0.rules.Literals



/*operator ::= math_op | comparison_op | boolean_op | ("|^&!:~")+
private math_op ::= "+" | "-" | "*" | "/" | "%"
private comparison_op ::= "=" | "<>" | "<" | ">" | "<=" | ">="
private boolean_op ::= "AND" | "OR" | "XOR" | "NOT"*/
